name: Demo-1 Workflow

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: run python msg
        run: echo "Now python is going to run"

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run python & Displying company name
        env:
          Company_name: ${{ secrets.Company_name }}
        run: python test.py

